
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: city_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: city_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: refer_seeds
    description: "Test reference of seeds"
    columns:
      - name: country_name
        description: "Acceptable values for Reference Table"
        tests:
          - accepted_values:
              values: ['United States', 'Canada', 'United Kingdom']  

  - name: seeds_employee_id
    description: "Test reference of seeds"
    columns:
      - name: employee_id
        description: "Acceptable values for Reference Table"
        tests:
          - accepted_values:
              values: [1,2,3,4,5]
