version: 2

seeds:
  - name: country_codes
    description: A mapping of two letter country codes to country names
    columns:
      - name: country_code
        tests:
          - unique
          - not_null
      - name: country_name
        tests:
          - unique
          - not_null
  - name: employee_ids
    description: A lookup table which contains only employee id
    columns:
      - name: employee_id
        tests:
          - unique
          - not_null
      